version: '3.8'

services:
  backend:
    container_name: backend
    build: ./livros-backend-main
    ports:
      - 4444:4444
    env_file:
      - ./livros-backend-main/.env
    depends_on:
      - mysql
    volumes:
      - ./livros-backend-main/log:/log
    networks:
      - rede_bd

  frontend:
    container_name: frontend
    build: ./livros-frontend-main
    ports:
      - 8000:80
    env_file:
      - ./livros-frontend-main/.env
    networks:
      - rede_bd
  
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - vol_mysql:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: webacad123
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: allan
      MYSQL_PASSWORD: allan123
    networks:
      - rede_bd

  bd_gui:
    container_name: bd_gui
    image: phpmyadmin:latest
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=webacad123
    networks:
      - rede_bd

networks:
  rede_bd:
    driver: bridge

volumes:
  vol_mysql: